### ISSUE TITLE
ArgumentNullException with Unity 2017.1

### ISSUE THREAD

**Issue by CCludts** [SaladbowlCreative/Unity3D.IncrementalCompiler#37]
I managed to build using #34, but get an error when I try to compile inside Unity.
Using Unity2017.1.1f1, windows 10 64bit.

```
ArgumentNullException: Argument cannot be null.
Parameter name: source
System.Linq.Check.SourceAndPredicate (System.Object source, System.Object predicate)
System.Linq.Enumerable.Single[CustomScriptAssembly] (IEnumerable`1 source, System.Func`2 predicate)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.CompileScripts (EditorScriptCompilationOptions definesOptions, BuildTargetGroup platformGroup, BuildTarget platform) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:322)
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.TickCompilationPipeline (EditorScriptCompilationOptions options, BuildTargetGroup platformGroup, BuildTarget platform) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:518)
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface.TickCompilationPipeline (EditorScriptCompilationOptions options, BuildTargetGroup platformGroup, BuildTarget platform) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilationInterface.cs:122)
```

I'm trying to build a single c# file in an empty project, so it shouldnt be anything related to extensions or things like that.

It seems that Unity is complaining about multiple programming languages being used at the same time.
I found that the compilerPlugin.dll is using CustomCSharpLanguage, so this might be related...?

Any tips would be very much appreciated.

**Comment by qbit86** [comment]
> ArgumentNullException: Argument cannot be null.
> Parameter name: source

@CCludts How did you work around this?

**Comment by CCludts** [comment]
> > ArgumentNullException: Argument cannot be null.
> > Parameter name: source
> 
> @CCludts How did you work around this?

I didnt manage to get it to work. Unity 2018.3(beta) has incremental compiling built-in though
